"""
Pipeline Context - Centralized state management for the DCC pipeline.
"""
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional


@dataclass
class PipelinePaths:
    """Paths used and generated by the pipeline."""
    base_path: Path
    schema_path: Path
    excel_path: Path
    csv_output_path: Path
    excel_output_path: Path
    summary_path: Path
    debug_log_path: Path


@dataclass
class PipelineBlueprint:
    """
    The Rulebook - Immutable storage for schema definitions and business rules.
    Loaded once during initiation/schema resolution.
    """
    columns: Dict[str, Any] = field(default_factory=dict)        # The 48-column blueprint
    error_catalog: Dict[str, Any] = field(default_factory=dict)  # Standardized error definitions
    phase_map: Dict[str, List[str]] = field(default_factory=dict) # P1-P4 column groupings
    validation_rules: Dict[str, Any] = field(default_factory=dict) # Global logic flags
    
    def get_columns_by_phase(self, phase: str) -> List[str]:
        """Return list of column names for a specific processing phase."""
        return self.phase_map.get(phase, [])


@dataclass
class PipelineTelemetry:
    """
    Performance Trace - Tracking execution time, row counts, and KPIs.
    """
    execution_times: Dict[str, float] = field(default_factory=dict) # engine_name: seconds
    data_metrics: Dict[str, Any] = field(default_factory=dict)      # rows, null_rates, etc.
    memory_usage: Dict[str, Any] = field(default_factory=dict)      # peak usage stats


@dataclass
class PipelineState:
    """
    The Scoreboard - Mutable state objects and results generated during execution.
    """
    setup_results: Dict[str, Any] = field(default_factory=dict)
    schema_results: Dict[str, Any] = field(default_factory=dict)
    resolved_schema: Dict[str, Any] = field(default_factory=dict)
    mapping_result: Dict[str, Any] = field(default_factory=dict)
    error_summary: Dict[str, Any] = field(default_factory=dict)
    environment: Dict[str, Any] = field(default_factory=dict)      # OS/Env snapshot
    engine_status: Dict[str, str] = field(default_factory=dict)     # engine: status (complete/failed)


@dataclass
class PipelineData:
    """Dataframes managed during pipeline execution."""
    df_raw: Optional[Any] = None  # pandas DataFrame
    df_mapped: Optional[Any] = None  # pandas DataFrame
    df_processed: Optional[Any] = None  # pandas DataFrame


@dataclass
class PipelineContext:
    """
    Centralized context object for the DCC pipeline.
    The Single Source of Truth (SSOT).
    """
    paths: PipelinePaths
    parameters: Dict[str, Any]
    blueprint: PipelineBlueprint = field(default_factory=PipelineBlueprint)
    state: PipelineState = field(default_factory=PipelineState)
    telemetry: PipelineTelemetry = field(default_factory=PipelineTelemetry)
    data: PipelineData = field(default_factory=PipelineData)
    
    # Execution flags
    nrows: Optional[int] = None
    debug_mode: bool = False
