"""
Pipeline Context - Centralized state management for the DCC pipeline.
"""
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional


@dataclass
class PipelinePaths:
    """Paths used and generated by the pipeline."""
    base_path: Path
    schema_path: Path
    excel_path: Path
    csv_output_path: Path
    excel_output_path: Path
    summary_path: Path
    debug_log_path: Path


@dataclass
class PipelineState:
    """State objects and results generated during pipeline execution."""
    setup_results: Dict[str, Any] = field(default_factory=dict)
    schema_results: Dict[str, Any] = field(default_factory=dict)
    resolved_schema: Dict[str, Any] = field(default_factory=dict)
    mapping_result: Dict[str, Any] = field(default_factory=dict)
    error_summary: Dict[str, Any] = field(default_factory=dict)


@dataclass
class PipelineData:
    """Dataframes managed during pipeline execution."""
    df_raw: Optional[Any] = None  # pandas DataFrame
    df_mapped: Optional[Any] = None  # pandas DataFrame
    df_processed: Optional[Any] = None  # pandas DataFrame


@dataclass
class PipelineContext:
    """
    Centralized context object for the DCC pipeline.
    Replaces loose variable passing between engines.
    """
    paths: PipelinePaths
    parameters: Dict[str, Any]
    state: PipelineState = field(default_factory=PipelineState)
    data: PipelineData = field(default_factory=PipelineData)
    
    # Execution flags
    nrows: Optional[int] = None
    debug_mode: bool = False
